POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Another note",
  "important": false,
  "userId": "605888228ada9f17460ff1e6"
}

###

// Fail mongoose validation rules
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "lol",
  "important": false,
  "userId": "605888228ada9f17460ff1e6"
}