POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdodW9uZyIsImlkIjoiNjA1ODg4MjI4YWRhOWYxNzQ2MGZmMWU2IiwiaWF0IjoxNjE2NDQ5NjYyfQ.10_IMwl0gWGAEseVgqsMJG8oISA57lLj_ivClUOcXeA

{
  "content": "Another note",
  "important": false,
  "userId": "605888228ada9f17460ff1e6"
}

###

// Fail mongoose validation rules
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "lol",
  "important": false,
  "userId": "605888228ada9f17460ff1e6"
}